version: '2'
services:
    myserver-app:
        image: myserver
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://myserver-mysql:3306/myserver?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    myserver-mysql:
        extends:
            file: mysql.yml
            service: myserver-mysql
